version: '3.8'

services:
  # API Gateway
  api-gateway:
    image: kien2201/studytracker/api-gateway:latest  # Thay thế bằng image của bạn
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - microservices-network
    depends_on:
      - identity-service
      - profile-service
      - notification-service
      - schedule-service

  # Identity Service (MySQL)
  identity-service:
    image: kien2201/studytracker/identity-service:latest  # Thay thế bằng image của bạn
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/identity_service
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - JWT_SIGNERKEY=1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
      - JWT_VALID-DURATION=3600
      - JWT_REFRESHABLE-DURATION=36000
      - APP_SERVICES_PROFILE=http://profile-service:8081/profile
    networks:
      - microservices-network
    depends_on:
      - mysql
      - kafka

  # Profile Service (MongoDB)
  profile-service:
    image: kien2201/studytracker/profile-service:latest  # Thay thế bằng image của bạn
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/profile-service?authSource=admin
    networks:
      - microservices-network
    depends_on:
      - mongodb

  # Notification Service (MongoDB + Kafka)
  notification-service:
    image: kien2201/studytracker/notification-service:latest  # Thay thế bằng image của bạn
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/notification-service?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP-SERVERS=kafka:9092
      - SPRING_KAFKA_CONSUMER_GROUP-ID=notification-group
      - NOTIFICATION_EMAIL_BREVO-URL=https://api.brevo.com
      - NOTIFICATION_EMAIL_BREVO-APIKEY=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 # Thay thế bằng API key của bạn
    networks:
      - microservices-network
    depends_on:
      - mongodb
      - kafka

  # Schedule Service (MongoDB)
  schedule-service:
    image: kien2201/studytracker/schedule-service:latest  # Thay thế bằng image của bạn
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:root@mongodb:27017/schedule-service?authSource=admin
    networks:
      - microservices-network
    depends_on:
      - mongodb

  # MySQL for Identity Service
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=identity_service
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices-network

  # MongoDB for Profile, Notification, and Schedule Services
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb-data:/data/db
    networks:
      - microservices-network

  # Kafka
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka-v1
    hostname: kafka
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-data:
  mongodb-data: