server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:

    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: schedule-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/schedules/**
          filters:
            - StripPrefix=2
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=2


springdoc:
  api-docs:
    enabled: true
    path: ${app.api-prefix}/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: "${app.api-prefix}/identity/v3/api-docs"
        name: "Identity Service"
      - url: "${app.api-prefix}/profile/users/v3/api-docs"
        name: "Profile Service"
      - url: "${app.api-prefix}/notification/v3/api-docs"
        name: "Notification Service"
      - url: "${app.api-prefix}/schedules/v3/api-docs"
        name: "Schedule Service"
      - url: "${app.api-prefix}/orders/v3/api-docs"
        name: "Order Service"
