server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/profile-service?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true