server:
  port: 8084
  servlet:
    context-path: /orders
spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/order-service?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  services:
    product: http://localhost:8083/products
    identity: http://localhost:8080/identity
  mapbox:
    access-token: pk.eyJ1Ijoia2llbjIyMDEiLCJhIjoiY200ODloNHlnMGRhajJwczltYTl3Z29laCJ9.0qMJiM-W99fbRV5vEGuoeg
