server:
  port: 8083
  servlet:
    context-path: /products
spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/product-service?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true