server:
  port: 8084
  servlet:
    context-path: /chats
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/chat-service?authSource=admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  services:
    identity: http://localhost:8080/identity